### ISSUE TITLE
SSL Cert werkt niet (Windows 10?)

### ISSUE THREAD

**Issue by benninkcorien** [Sjors/crush_curve#10]
Error code: SSL_ERROR_PROTOCOL_VERSION_ALERT
in Firefox, Chrome en Edge voor pletdecurve.nl

(en git clone op Ubuntu proberen te draaien geeft ook fouten. Jammer, want erg handige site!)

**Comment by Sjors** [comment]
Kan je een apart issue maken voor de fouteen die je op Ubuntu ziet met een lokale server? Die gebruikt namelijk geen https. Misschien dat ik een stap vergeten ben in de README.

Welke versie van Firefox, Chrome en Edge gebruik je? Het zou kunnen dat ik nginx wat te strict heb ingesteld, m.n. sommige oude browsers ondersteunen TLSv1.3 niet:

```
ssl_protocols TLSv1.3;
ssl_prefer_server_ciphers on;
ssl_dhparam /home/crush/dhparams.pem;
ssl_ciphers EECDH+AESGCM:EDH+AESGCM;
ssl_ecdh_curve secp384r1; # Requires nginx >= 1.1.0
ssl_session_timeout  10m;
ssl_session_cache shared:SSL:10m;
ssl_session_tickets off; # Requires nginx >= 1.5.9
ssl_stapling on; # Requires nginx >= 1.3.7
ssl_stapling_verify on; # Requires nginx => 1.3.7
```

**Comment by benninkcorien** [comment]
## Firefox 80.0 

    Secure Connection Failed
    An error occurred during a connection to pletdecurve.nl. Peer reports incompatible or unsupported protocol version.
    Error code: SSL_ERROR_PROTOCOL_VERSION_ALERT

        The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
        Please contact the website owners to inform them of this problem.
   
    Learn more…
    This website might not support the TLS 1.2 protocol, which is the minimum version supported by Firefox. Enabling TLS 1.0 and TLS    1.1 might allow this connection to succeed.

    TLS 1.0 and TLS 1.1 will be permanently disabled in a future release.

## Chrome Version 85.0.4183.83

    This site can’t provide a secure connection
     pletdecurve.nl uses an unsupported protocol.
     ERR_SSL_VERSION_OR_CIPHER_MISMATCH

Ik zal een nieuwe voor de Ubuntu aanmaken (was iets met de PG nogwat gem, en een server die niet gevonden kon worden.)

**Comment by benninkcorien** [comment]
Edit: op mijn telefoon (Android) werkt de site wel goed (in Brave).

**Comment by Sjors** [comment]
Vreemd, ik heb zelf ook Firefox 80 en Chrome, maar dan op macOS. Is er toevallig een `Advanced...` met meer details, zoals [hier](https://support.mozilla.org/en-US/kb/secure-connection-failed-firefox-did-not-connect)?

**Comment by benninkcorien** [comment]
Nee, geen Advanced helaas, ook geen info in de Console of Netwerk tab.
Wel een knop met "Enable TLS 1.0 and 1.1" maar die doet weinig verder.
 
Antivirus en adblock uit helpt niet, maar ik heb net even gekeken en op mijn laptop werkt hij ook gewoon goed in Firefox. 
Sluit maar deze, geen idee waar het aan ligt, maar waarschijnlijk iets raars in mijn PC (Windows 10) dan?

**Comment by Sjors** [comment]
> Wel een knop met "Enable TLS 1.0 and 1.1" maar die doet weinig verder.

Nee, dat is het vreemde aan die warning; de site ondersteunt alleen 1.3, dus een knop om 1.0 of 1.1 te gebruiken, zou inderdaad niks moeten doen.

> Sluit maar deze

Ik laat hem nog even open, want ik heb dit issue eerder gehoord.

**Comment by benninkcorien** [comment]
Oh, zeg dan maar wat ik kan doen om te zoeken waar het aan ligt!

**Comment by Sjors** [comment]
Niks, laten we gewoon even afwachten of iemand anders (via Google) langs dit issue komt.
