### ISSUE TITLE
db:rake werkt niet op Linux

### ISSUE THREAD

**Issue by benninkcorien** [Sjors/crush_curve#11]
Geprobeerd om alles PopOS! 20.04 LTS (ID_Like: ubuntu debian) op localhost werkend te krijgen. Gaf wat problemen.
 
> update ruby van 2.7.0 naar 2.7.1
uitleg op https://www.itzgeek.com/post/how-to-install-ruby-on-rails-on-ubuntu-20-04/

> bundle install
gaf eerst foutmelding voor pg 1.2.3

heb toen eerst handmatig 
> sudo apt-get install libpq-dev
geïnstalleerd.

Toen gingen alle bundle dingen goed.

> rake db:seed

geeft nog een foutmelding:

    PG::ConnectionBad: FATAL: role "mijnusername" does not exist

> rails s 

werkt wel maar localhost:3000 riep

    PG:ConnectionBad.
    Could  not connect to server: no such file or directory. ise the server running locally and acception connections in Unix domain socket var/run/postgresql 5432 ?

> sudo service postgresql start

lost dat op. Maar dan blijft ook daar 

    FATAL: role 'mijnusername" does not exist.

En toen heb ik het opgegegeven. Ben niet heel goed  met ruby ook verder.

**Comment by Sjors** [comment]
Je hebt Postgres nodig. Daarna zou "bundle install" wel moeten werken. Wellicht moet je ook eerst `rake db:create` aanroepen, da's i.i.g. een goede manier om te zien over Postgres aanwezig is en er verder geen configuratie / permission probleem is.

**Comment by benninkcorien** [comment]
Ah, postgresql wel geïnstalleerd, maar ik moest nog

> sudo -u postgres createuser --superuser mijnusername

doen

db:seed werkt nu!

**Comment by Sjors** [comment]
Postgres is een bron van hoofdpijn, maar goed dat die oneliner werkte. Nu zou je de RIVM data moeten kunnen fetchen en processen en dan lokaal hetzelfde zien als of de site.

**Comment by benninkcorien** [comment]
Vooruitgang. Hij zegt nu dat er voor vandaag nog geen nieuwe gegevens zijn. 
Ik probeer het vanavond nog wel een keer, maar nu de site werkt op mobiel en laptop is localhost niet heel erg nodig meer (dus als dit voor jou weinig toevoegt qua documentatie kan deze dicht, dan pruts ik zelf wel verder tot het werkt).

**Comment by Sjors** [comment]
Mmm, ik denk dat die foutmelding niet klopt. I.p.v. `rake data:fetch`, probeer eens `rake data:fetch[true]`.

Post gerust vervolgvragen, maar ik sluit het issue alvast.
