### ISSUE TITLE
Site no longer active?

### ISSUE THREAD

**Issue by hbokh** [Sjors/crush_curve#35]
@Sjors Is there a reason the site is no longer available? I personally liked it very much.
Resolving / checking DNS doesn't come up with an A (or AAAA) address.

```
$ host www.pletdecurve.nl
Host www.pletdecurve.nl not found: 3(NXDOMAIN)
```

**Comment by Sjors** [comment]
Unfortunately the site is indeed no longer active. It was designed with a zero-covid strategy mind, but that's clearly not happening at this point. So I no longer think it's worth the server cost and maintenance effort. Perhaps someone else can host it though.

**Comment by hbokh** [comment]
Thanks for answering, Sjors.
